

llm_config:
    system_message: "You will be given the user question along with the search result of that question over a Neo4j graph database. Give the user the proper answer."
    model_name: "gpt-35-turbo-1106"
    embedding_model_name: "text-embedding-ada-002"
    temperature: 0.0
    

RAG_config:
  top_k: 5